name: power_image
description: A powerful plugin that fully uses the native image library's ability to display images on the flutter side.
version: 0.1.0-pre.2
homepage: https://github.com/alibaba/power_image

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter
  power_image_ext: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.taobao.power_image
        pluginClass: PowerImagePlugin
      ios:
        pluginClass: PowerImagePlugin